apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-demo1"
  description: tbc update later
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    github.com/project-slug: hs14428/backstage
    # terraform.io/organization: ''
    terraform.io/project: 'backstage-test-398910'
    terraform.io/workspace: 'backstage-demo1'
  links:
    - url: "https://console.cloud.google.com/compute/instancesDetail/zones//instances/?project="
spec:
  type: service
  owner: hs14428
  lifecycle: dev
