apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "compute-engine1"
  description: A google cloud compute engine instance
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    github.com/project-slug: hs14428/backstage
    # terraform.io/organization: ''
    terraform.io/project: 'backstage-demo-393313'
    terraform.io/workspace: 'compute-engine1'
  links:
    - url: "https://console.cloud.google.com/compute/instancesDetail/zones/europe-west2-c/instances/compute-engine1?project=backstage-demo-393313"
spec:
  type: service
  owner: user:harry.smith
  lifecycle: dev
