apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.instanceName | dump }}
  description: A google cloud compute engine instance
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo_name }}
    # terraform.io/organization: '${{ values.organization }}'
    terraform.io/project: '${{ values.projectId }}'
    terraform.io/workspace: '${{ values.instanceName }}'
  links:
    - url: "https://console.cloud.google.com/compute/instancesDetail/zones/${{ values.deploymentZone }}/instances/${{ values.instanceName }}?project=${{ values.projectId }}"
spec:
  type: service
  owner: user:harry.smith
  lifecycle: ${{ values.deploymentEnvironment }}
